### PR TITLE
Mccalluc/factor out ingest

### PR DESCRIPTION
**Pull request by mccalluc**
@pkerpedjiev : I think this works, but there's a lot which is questionable. For now, I'm going to work on migrating the bash tests to python, and adding more commandline arg support. I should also check that data ingested this way can actually be retrieved.

### CODE REVIEW

**Comment by mccalluc** [comment]
Replaced the curl upload with the commandline in the README: since the curl needs a user to be created, telling that whole story makes things look more complicated than they really are. In a separate section or a separate doc on the API, sure.

@pkerpedjiev : If this looks good to you, can it be merged and tagged? Or if there are outstanding issues, what are they? I'd like to incorporate this in the docker container. Thanks!

**Comment by mccalluc** [comment]
(The whole bash wrapper for the tests is ugly. I'd probably work on moving that into setUp, though there's probably something more important to work on?)

**Comment by pkerpedjiev** [comment]
Merged with develop. Tests run when started using `test.sh` but not when running `python manage.py test higlass_server`.  I guess this is because there needs to be some setup done first?

Would it be possible to make the unit tests independent?

**Comment by pkerpedjiev** [comment]
The tests also create an `uploads` directory in the root `higlass-server` directory. Can this be placed in `/tmp` and removed when the tests finished? 

Same for `db_test.sqlite3`.

**Pull request merged**
